apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking-service
          image: your-dockerhub/tracking-service:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/tracking/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  selector:
    app: tracking
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
